export const DATABASE_CONNECTION = 'DATABASE_CONNECTION';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const EXPENSE_REPOSITORY = 'EXPENSE_REPOSITORY';
export const NOTE_REPOSITORY = 'NOTE_REPOSITORY';
export const TAG_REPOSITORY = 'TAG_REPOSITORY';
