version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    volumes:
      - "./src:/home/app/src"
    ports:
      - "3000:3000"
      - "9229:9229"

  postgres:
    image: postgres:11.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
